Lab 9 Game of Life: gameoflife.c File Reference
gameoflife.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <omp.h>
Macros
#define for_x for (int x = 0; x < w; x++)
#define for_y for (int y = 0; y < h; y++)
#define for_xy for_x for_y
Functions
void show (void *u, int w, int h)
Show current state of grid after evolving function.
void evolve (void *u, int w, int h)
Kill or birth a cell function.
void game (int w, int h)
Main game function.
int main (int c, char **v)
Main function of the code.
Macro Definition Documentation
for_x
#define for_x for (int x = 0; x < w; x++)
Definition at line 6 of file gameoflife.c.
for_xy
#define for_xy for_x for_y
Definition at line 8 of file gameoflife.c.
for_y
#define for_y for (int y = 0; y < h; y++)
Definition at line 7 of file gameoflife.c.
Function Documentation
evolve()
void evolve (void * u, int w, int h)
Kill or birth a cell function.
Definition at line 25 of file gameoflife.c.
{
    unsigned (*univ)[w] = u;
    unsigned new[h][w];
        #pragma omp parallel for_y for_x
    for_y for_x {
        int n = 0;
                #pragma omp parallel for
        for (int y1 = y - 1; y1 <= y + 1; y1++)
                    #pragma omp parallel for
            for (int x1 = x - 1; x1 <= x + 1; x1++)
                if (univ[(y1 + h) % h][(x1 + w) % w])
                    n++;
        if (univ[y][x]) n--;
        new[y][x] = (n == 3 || (n == 2 && univ[y][x]));
    }
        #pragma omp parallel for_y for_x
    for_y for_x univ[y][x] = new[y][x];
}
References for_x, and for_y.
Referenced by game().
game()
void game (int w, int h)
Main game function.
Definition at line 48 of file gameoflife.c.
{
    unsigned univ[h][w];
        #pragma omp parallel for_xy
    for_xy univ[y][x] = rand() < RAND_MAX / 10 ? 1 : 0;
        #pragma omp parallel while
    while (1) {
        show(univ, w, h);
        evolve(univ, w, h);
        usleep(200000);
                #pragma omp barrier
    }
}
References evolve(), for_xy, and show().
Referenced by main().
main()
int main (int c, char ** v)
Main function of the code.
Definition at line 63 of file gameoflife.c.
{
    int w = 0, h = 0;
    if (c > 1) w = atoi(v[1]);
    if (c > 2) h = atoi(v[2]);
    if (w <= 0) w = 30;
    if (h <= 0) h = 30;
    game(w, h);
}
References game().
show()
void show (void * u, int w, int h)
Show current state of grid after evolving function.
Definition at line 11 of file gameoflife.c.
{
    int (*univ)[w] = u;
    printf("\033[H");
        #pragma omp parallel for_y
    for_y {
            #pragma omp parallel for_x
        for_x printf(univ[y][x] ? "\033[07m  \033[m" : "  ");
        printf("\033[E");
    }
    fflush(stdout);
}
References for_x, and for_y.
Referenced by game().