Lab 10 Stencil: stencil.cpp File Reference
stencil.cpp File Reference
#include <iostream>
#include <stdlib.h>
#include <complex>
#include <time.h>
#include <functional>
#include <limits>
#include <vector>
Functions
int calcNeighbours (vector< float > const &in, int index, vector< float > &out)
Function to calculate the neighbours of the vector list.
void stencil (vector< float > const &in, vector< float > &out, function< float(vector< float >) > f, int size)
Stencil function.
float getNewValue (vector< float > currentValues)
Function to get new total value.
int main (void)
Main function of the code.
Variables
const int DIM =1000
const int SIZE =4
Function Documentation
calcNeighbours()
int calcNeighbours (vector< float > const & in, int index, vector< float > & out)
Function to calculate the neighbours of the vector list.
Definition at line 65 of file stencil.cpp.
{
  int amount=out.size();
  for(int i=0;i<out.size();++i){//put neighbours of in[i] into out vector
    int k=i-amount/2;
    if (k<0){//wrap k around size of in vector
      k=in.size()+k;
    }else if (k>=in.size()){
      k=k-in.size();
    }
    out[i]=in[k];
  }
  return 1;
}
Referenced by stencil().
getNewValue()
float getNewValue (vector< float > currentValues)
Function to get new total value.
Definition at line 93 of file stencil.cpp.
{
  float average=0.0;
  float total=0.0;
  for(auto const& value: currentValues){
    total+=value;
  }
  return total/currentValues.size();
}
Referenced by main().
main()
int main (void)
Main function of the code.
Definition at line 103 of file stencil.cpp.
              {
  vector<float> first(DIM), second(DIM);
  //initilise vectors
  srand (time(NULL));
  for(auto& value: first) {
    value=(float)rand() / ((float)(RAND_MAX)+(float)(1));
  }
  for(auto it=second.begin(); it<second.end();++it){
    *it=0.0f;
  }
  //
  float sum=0.0f;
  for(auto const&value: first){
    sum+=value;
  }
  cout << sum <<endl;
  stencil(first,second,getNewValue,SIZE);
  sum=0.0f;
  for(auto const&value: second){
    sum+=value;
  }
  cout << sum <<endl;
  return 0;
}
References DIM, getNewValue(), SIZE, and stencil().
stencil()
void stencil (vector< float > const & in, vector< float > & out, function< float(vector< float >) > f, int size)
Stencil function.
Definition at line 80 of file stencil.cpp.
{
#pragma openmp parallel for
  for (int i=0; i < in.size(); ++i){
    vector<float> neighbours(size);
    calcNeighbours(in,i,neighbours);
    out[i]=f(neighbours);
  }
}
References calcNeighbours().
Referenced by main().
Variable Documentation
DIM
const int DIM =1000
Definition at line 61 of file stencil.cpp.
Referenced by main().
SIZE
const int SIZE =4
Definition at line 62 of file stencil.cpp.
Referenced by main().