Lab 10 Maps: mandelbroit.cpp File Reference
mandelbroit.cpp File Reference
#include <iostream>
#include <stdlib.h>
#include <complex>
#include <time.h>
#include <limits>
#include <omp.h>
Functions
int calc (complex< int > c, int depth)
void mandel (int p[ROW][COL], int depth)
int main (void)
Variables
const int ROW =1000
const int COL =1000
const int DEPTH =1000
Function Documentation
calc()
int calc (complex< int > c, int depth)
Definition at line 61 of file mandelbroit.cpp.
{
    int count=0;
    complex<int> z=0;
    for(int i=0;i<depth;++i){
    if (abs(z)>2.0){
            break;
    }
    z=z*z+c;
    count++;
    }
    return count;
}
Referenced by mandel().
main()
int main (void)
Definition at line 84 of file mandelbroit.cpp.
              {
  int myArray[ROW][COL];
  /* initialize random seed: */
  srand (time(NULL));
  clock_t begin = clock();
  mandel(myArray,DEPTH);
  clock_t end = clock();
  double timeSec = (end - begin) / static_cast<double>( CLOCKS_PER_SEC );
  std::cout << timeSec << std::endl;
}
References COL, DEPTH, mandel(), and ROW.
mandel()
void mandel (int p[ROW][COL], int depth)
Definition at line 75 of file mandelbroit.cpp.
{
  #pragma omp parallel for collapse(2)
  for(int i=0;i<ROW;++i){
        for(int k=0;k<COL;++k){
      p[i][k]=calc(complex<int>(i,k),depth);
    }
    }
}
References calc(), COL, and ROW.
Referenced by main().
Variable Documentation
COL
const int COL =1000
Definition at line 58 of file mandelbroit.cpp.
Referenced by main(), and mandel().
DEPTH
const int DEPTH =1000
Definition at line 59 of file mandelbroit.cpp.
Referenced by main().
ROW
const int ROW =1000
Definition at line 57 of file mandelbroit.cpp.
Referenced by main(), and mandel().